# Supabase Configuration File
# Project: B767 Fleet Management (wgdmgvonqysflwdiiols)

project_id = "wgdmgvonqysflwdiiols"

[auth]
# Site URL - Primary production URL
site_url = "https://fleet-management-v2.vercel.app"

# Additional redirect URLs (comma-separated list)
additional_redirect_urls = [
  "https://fleet-management-v2.vercel.app/**",
  "https://fleet-management-v2-rondeaumaurice-5086s-projects.vercel.app/**",
  "http://localhost:3000/**"
]

# Enable signup
enable_signup = true

# JWT settings
jwt_expiry = 3600

# Auth providers
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.google]
enabled = false

[auth.external.github]
enabled = false
